### ISSUE TITLE
remove extra <br>s around images

### ISSUE THREAD

**Issue by meetar** [mapzen/documentation#267]
Seeing some extra space between code blocks and images in a docs page (https://precog.mapzen.com/mapzen/documentation/meetar/unembed-tutorial2/documentation/tangram/custom-styles/):

<img width="715" alt="screen shot 2017-03-01 at 1 51 27 pm" src="https://cloud.githubusercontent.com/assets/459970/23475719/61f7078c-fe86-11e6-8171-59a9fff37ad8.png">

Markdown code looks like this:

<pre>
```yaml
sources:
    mapzen:
        type: TopoJSON
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson

layers:
    roads:
        data: { source: mapzen }
        draw:
            lines:
                order: 1
                width: 5px
                color: gray
```
![simple road map](https://tangrams.github.io/tangram-docs/tutorials/custom/custom1.jpg)
</pre>

And resulting html looks like this in the dev pane:

<img width="449" alt="screen shot 2017-03-01 at 1 52 08 pm" src="https://cloud.githubusercontent.com/assets/459970/23476241/2b3fb8e0-fe88-11e6-8983-a79809564d55.png">

I'm seeing `<br>` tags on either side of the `<img>` – would it be possible to remove those from the build process?
